dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='latest' BUILD_PATH='python3.7' TEST_STR1='Hello World from a default Python 3.7 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.7'
  - NAME='python3.7' BUILD_PATH='python3.7' TEST_STR1='Hello World from a default Python 3.7 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.7'
  - NAME='python3.6' BUILD_PATH='python3.6' TEST_STR1='Hello World from a default Python 3.6 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.6'
  - NAME='python2.7' BUILD_PATH='python3.6' TEST_STR1='Hello World from a default Python 2.7 app in a Docker container, with Meinheld and Gunicorn (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 2.7'
  - NAME='python3.7-alpine3.8' BUILD_PATH='python3.7-alpine3.8' TEST_STR1='Hello World from a default Python 3.7 app in a Docker container, with Meinheld and Gunicorn on Alpine (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.7'
  - NAME='python3.6-alpine3.8' BUILD_PATH='python3.6-alpine3.8' TEST_STR1='Hello World from a default Python 3.6 app in a Docker container, with Meinheld and Gunicorn on Alpine (default)' TEST_STR2='Test app. From Meinheld with Gunicorn. Using Python 3.6'

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
